### ISSUE TITLE
Repo Description

### ISSUE THREAD

**Issue by bim-g** [nevolut/phone-cd#1]
Hello!
Hope you are dong well!.
can you just a simple description of your repository to make sure people can have an idea of the project is for?.
Thanks.

**Comment by YvesKalume** [comment]
@bim-g the issue should be : « why do you use a auto commit bot ? » 😄

**Comment by Abarchibody** [comment]
The project handle validation and number format of the DRC phone number.

**Comment by bim-g** [comment]
@YvesKalume to use the auto commit bot is not my problem, i dont know why he did it.

**Comment by bim-g** [comment]
> The project handle validation and number format of the DRC phone number.

i think you should also add it on the repo description. and if possible why not host it on npm so that congo dev you use it in stead of rewrite those module every time?

**Comment by bim-g** [comment]
> > The project handle validation and number format of the DRC phone number.
> 
> i think you should also add it on the repo description. and if possible why not host it on npm so that congo dev you use it in stead of rewrite those module every time?
